Cleaning up SysV script

diff --git a/debian/init b/debian/init
--- a/debian/init
+++ b/debian/init
@@ -1,112 +1,62 @@
-#!/bin/sh
+#! /bin/sh
 ### BEGIN INIT INFO
-# Provides:          node_debian_init
-# Required-Start:    $remote_fs $named $syslog
-# Required-Stop:     $remote_fs $named $syslog
+# Provides:          node-js-sample
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: DEBIAN initscript for node.js servers/apps
-# Description:       ex : proxy server is a node.js http server listening on
-#                    port 8080 (relayed from 80 by iptables). It balances
-#                    http requests between the main nodejs server 
-#                    (nodejs.mydomain.com:8000), the static file-server 
-#                    (static.mydomain.com) and the legacy apache server
-#                    (apache.mydomain.com) and possibly other servers
-#                    place this file in /etc/init.d.
+# Short-Description: Node.js sample application
+# Description:       This is a sample node.js application
 ### END INIT INFO
 
-PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
-DAEMON_ARGS="/usr/share/node-js-sample"
+# Author: Mike Palmer <mike@mikepalmer.net>
+
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="Sample node.js service"
-NODEUSER=root:root
-LOCAL_VAR_RUN=/var/run                      # in case the init script is run by non-root user, you need to
-                                            # indicate a directory writeable by $NODEUSER to store the PID file
-                                            # NB : 1) /usr/local/var/run does not exist by DEFAULT. Either create it
-                                            #      or choose one of your own liking.
-                                            #      2) node, npm,... are best NOT installed/run as ROOT.
-                                            #         (see here: https://github.com/isaacs/npm/blob/master/README.md)
+NAME=node-js-sample
+DAEMON=/usr/bin/nodejs
+APPLICATION="/usr/share/node-js-sample"
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
+USER=www-data
 
-NAME=nodejs                                 # name of the node.js executable
-DAEMON=/usr/bin/$NAME                       # this SHOULD POINT TO where your node executable is
+[ -x "$DAEMON" ] || exit 0
 
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-
-
-# Do NOT "set -e"
-
-[ $UID -eq "0" ] && LOCAL_VAR_RUN=/var/run # in case this script is run by root, override user setting
-THIS_ARG=$0
-INIT_SCRIPT_NAME=`basename $THIS_ARG`
-[ -h $THIS_ARG ] && INIT_SCRIPT_NAME=`basename $(readlink $THIS_ARG)` # in case of symlink
-INIT_SCRIPT_NAME_NOEXT=${INIT_SCRIPT_NAME%.*}                            
-PIDFILE="$LOCAL_VAR_RUN/$INIT_SCRIPT_NAME_NOEXT.pid"
-SCRIPTNAME=/etc/init.d/$INIT_SCRIPT_NAME
-
-# Exit if the package is not installed
-[ -x "$DAEMON" ] ||  { echo "can't find Node.js ($DAEMON)"  >&2; exit 0; }
-
-# Exit if the 'run' folder is not present
-[ -d "$LOCAL_VAR_RUN" ] || { echo "Directory $LOCAL_VAR_RUN does not exist. Modify the '$INIT_SCRIPT_NAME_NOEXT' init.d script ($THIS_ARG) accordingly" >&2; exit 0; }
-
-# Read configuration variable file if it is present
-[ -r /etc/default/$INIT_SCRIPT_NAME ] && . /etc/default/$INIT_SCRIPT_NAME
-
-# Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
-
-# Define LSB log_* functions.
-# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
-
-# uncomment to override system setting
-# VERBOSE=yes
 
 #
 # Function that starts the daemon/service
 #
-do_start()
-{
+do_start() {
 	# Return
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $NODEUSER --background --exec $DAEMON --test > /dev/null \
-		|| { [ "$VERBOSE" != no ] && log_daemon_msg  "  --->  Daemon already running $DESC" "$INIT_SCRIPT_NAME_NOEXT"; return 1; }
-	start-stop-daemon --start --quiet --chuid $NODEUSER --make-pidfile --pidfile $PIDFILE --background --exec $DAEMON -- \
-		$DAEMON_ARGS \
-		|| { [ "$VERBOSE" != no ] && log_daemon_msg  "  --->  could not be start $DESC" "$INIT_SCRIPT_NAME_NOEXT"; return 2; }
-	# Add code here, if necessary, that waits for the process to be ready
-	# to handle requests from services started subsequently which depend
-	# on this one.  As a last resort, sleep for some time.
-	[ "$VERBOSE" != no ] && log_daemon_msg  "  --->  started $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $USER --background --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --chuid $USER --make-pidfile --pidfile $PIDFILE --background --exec $DAEMON -- \
+		$APPLICATION \
+		|| return 2
 }
 
 #
 # Function that stops the daemon/service
 #
-do_stop()
-{
+do_stop() {
 	# Return
 	#   0 if daemon has been stopped
 	#   1 if daemon was already stopped
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE  --chuid $NODEUSER --name $DAEMON
+	start-stop-daemon --stop --quiet --retry=TERM/31/KILL/5 --pidfile $PIDFILE --chuid $USER --name `basename $DAEMON` 
 	RETVAL="$?"
-	#[ "$VERBOSE" != no ] && [ "$RETVAL" = 1 ] && log_daemon_msg  "  --->  SIGKILL failed => hardkill $DESC" "$INIT_SCRIPT_NAME_NOEXT"
 	[ "$RETVAL" = 2 ] && return 2
-	# Wait for children to finish too if this is a daemon that forks
-	# and if the daemon is only ever run from this initscript.
-	# If the above conditions are not satisfied then add some other code
-	# that waits for the process to drop all resources that could be
-	# needed by services started subsequently.  A last resort is to
-	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/3/KILL/5 --pidfile $PIDFILE  --chuid $NODEUSER --exec $DAEMON -- $DAEMON_ARGS
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --chuid $USER --exec $DAEMON -- $APPLICATION
 	[ "$?" = 2 ] && return 2
-	# Many daemons don't delete their pidfiles when they exit.
 	rm -f $PIDFILE
-  [ "$VERBOSE" != no ] && [ "$RETVAL" = 1 ] && log_daemon_msg "  --->  $DESC not running" "$INIT_SCRIPT_NAME_NOEXT"
-  [ "$VERBOSE" != no -a "$RETVAL" = 0 ] && log_daemon_msg "  --->  $DESC stopped" "$INIT_SCRIPT_NAME_NOEXT"
 	return "$RETVAL"
 }
 
@@ -114,61 +64,13 @@ do_stop()
 # Function that sends a SIGHUP to the daemon/service
 #
 do_reload() {
-	#
-	# If the daemon can reload its configuration without
-	# restarting (for example, when it is sent a SIGHUP),
-	# then implement that here.
-	#
-	start-stop-daemon --stop --quiet --signal 1 --pidfile $PIDFILE  --chuid $NODEUSER --name $NAME
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --chuid $USER --name `basename $DAEMON` 
 	return 0
 }
 
-#
-# Function that returns the daemon 
-#
-do_status() {
-  #
-  # http://refspecs.freestandards.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
-  # 0 program is running or service is OK
-  # 1 program is dead and /var/run pid file exists
-  # (2 program is dead and /var/lock lock file exists) (not used here)
-  # 3 program is not running
-  # 4 program or service status is unknown
-  RUNNING=$(running)
-  
-  # $PIDFILE corresponds to a live $NAME process
-  ispidactive=$(pidof $NAME | grep `cat $PIDFILE 2>&1` >/dev/null 2>&1)
-  ISPIDACTIVE=$?
-
-  if [ -n "$RUNNING" ]; then
-    if [ $ISPIDACTIVE ]; then 
-      log_success_msg "$INIT_SCRIPT_NAME_NOEXT (launched by $USER) (--chuid $NODEUSER) is running"
-      exit 0      
-    fi
-  else
-    if [ -f $PIDFILE ]; then
-      log_success_msg "$INIT_SCRIPT_NAME_NOEXT (launched by $USER) (--chuid $NODEUSER) is not running, phantom pidfile $PIDFILE"
-      exit 1
-    else
-      log_success_msg "no instance launched by $USER, of $INIT_SCRIPT_NAME_NOEXT (--chuid $NODEUSER) found"
-      exit 3
-    fi
-  fi
-  
-}
-
-running() {
-  RUNSTAT=$(start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $NODEUSER --background --exec $DAEMON --test > /dev/null)
-  if [ "$?" = 1 ]; then
-    echo y
-  fi
-  
-}
-
-
 case "$1" in
   start)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
 	do_start
 	case "$?" in
 		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
@@ -176,28 +78,18 @@ case "$1" in
 	esac
 	;;
   stop)
-	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
 	do_stop
 	case "$?" in
 		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
 		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
 	;;
-  #reload|force-reload)
-	#
-	# If do_reload() is not implemented then leave this commented out
-	# and leave 'force-reload' as an alias for 'restart'.
-	#
-	#log_daemon_msg "Reloading $DESC" "$NAME"
-	#do_reload
-	#log_end_msg $?
-	#;;
+  status)
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	;;
   restart|force-reload)
-	#
-	# If the "reload" option is implemented then remove the
-	# 'force-reload' alias
-	#
-	log_daemon_msg "Restarting $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+	log_daemon_msg "Restarting $DESC" "$NAME"
 	do_stop
 	case "$?" in
 	  0|1)
@@ -209,18 +101,15 @@ case "$1" in
 		esac
 		;;
 	  *)
-	  	# Failed to stop
+		# Failed to stop
 		log_end_msg 1
 		;;
 	esac
 	;;
-  status)
-    do_status
-  ;;
   *)
-	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
 	exit 3
 	;;
 esac
 
-exit 0
+:
